export const stream_status = {
	LIVE_STOP: 0,
	LIVE_PAUSE: 0,
	LIVE_PLAYING: 1,
	LIVE_FAILED: -1,
	LIVE_BUFFERING: 2,
	LIVE_CONNECTING: 3,
	LIVE_RECONNECTING: 4,
	STREAM_GEOBLOCKED: -200,
	STREAM_GEO_BLOCKED_ALTERNATE: -201,
	STREAM_GEO_BLOCKED_NO_ALTERNATE: -202,
	STATION_NOT_FOUND: -300,
	PLAY_NOT_ALLOWED: -400,
};
